services:
  postgres:
    image: postgres:17
    container_name: marketing-factory-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketing_factory
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
