import { Template } from '../types';

// Plantilla de email marketing estilo Colsanitas
export const colsanitasEmailTemplate: Template = {
  id: 'colsanitas-email-001',
  name: 'Email Marketing - Colsanitas',
  type: 'mail',
  width: 600,
  height: 800,
  background: '#ffffff',
  sections: [
    {
      id: 'header',
      name: 'Header',
      description: 'Logo y encabezado principal',
      visible: true,
      locked: true,
      order: 1,
      elements: [
        {
          id: 'header-bg',
          type: 'color',
          x: 0,
          y: 0,
          width: 600,
          height: 80,
          fill: '#ffffff',
          sectionId: 'header',
          editable: false,
        },
        {
          id: 'logo-text',
          type: 'text',
          x: 30,
          y: 25,
          text: 'Colsanitas',
          fontSize: 24,
          fontFamily: 'Arial, sans-serif',
          fill: '#0B4B8A',
          sectionId: 'header',
          editable: false,
        },
      ],
    },
    {
      id: 'hero',
      name: 'Sección Principal',
      description: 'Contenido principal del email',
      visible: true,
      locked: false,
      order: 2,
      elements: [
        {
          id: 'hero-bg',
          type: 'color',
          x: 20,
          y: 100,
          width: 560,
          height: 300,
          fill: '#0B4B8A',
          radius: 12,
          sectionId: 'hero',
          editable: true,
        },
        {
          id: 'hero-title',
          type: 'text',
          x: 40,
          y: 140,
          width: 520,
          text: 'LOREM IPSUM\nDOLOR SIT AMET',
          fontSize: 32,
          fontFamily: 'Arial, sans-serif',
          fill: '#ffffff',
          align: 'left',
          sectionId: 'hero',
          editable: true,
        },
        {
          id: 'hero-subtitle',
          type: 'text',
          x: 40,
          y: 220,
          width: 300,
          text: 'Lorem ipsum dolor sit\nadipiscing elit, sed\ndolor sit amet, with\nlorem text overlay.',
          fontSize: 16,
          fontFamily: 'Arial, sans-serif',
          fill: '#ffffff',
          align: 'left',
          sectionId: 'hero',
          editable: true,
        },
        {
          id: 'hero-image',
          type: 'image',
          x: 400,
          y: 120,
          width: 160,
          height: 200,
          src: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDE2MCAyMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxNjAiIGhlaWdodD0iMjAwIiBmaWxsPSIjRjBGMEYwIi8+Cjx0ZXh0IHg9IjgwIiB5PSIxMDAiIGZpbGw9IiM5OTk5OTkiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+SW1hZ2VuPC90ZXh0Pgo8L3N2Zz4K',
          alt: 'Imagen principal',
          sectionId: 'hero',
          editable: true,
        },
      ],
    },
    {
      id: 'content',
      name: 'Contenido Secundario',
      description: 'Información adicional',
      visible: true,
      locked: false,
      order: 3,
      elements: [
        {
          id: 'content-text',
          type: 'text',
          x: 30,
          y: 440,
          width: 540,
          text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.',
          fontSize: 14,
          fontFamily: 'Arial, sans-serif',
          fill: '#333333',
          align: 'left',
          sectionId: 'content',
          editable: true,
        },
        {
          id: 'cta-button',
          type: 'color',
          x: 30,
          y: 520,
          width: 150,
          height: 45,
          fill: '#007acc',
          radius: 6,
          sectionId: 'content',
          editable: true,
        },
        {
          id: 'cta-text',
          type: 'text',
          x: 30,
          y: 532,
          width: 150,
          text: 'VER MÁS',
          fontSize: 14,
          fontFamily: 'Arial, sans-serif',
          fill: '#ffffff',
          align: 'center',
          sectionId: 'content',
          editable: true,
        },
      ],
    },
    {
      id: 'footer',
      name: 'Pie de página',
      description: 'Información de contacto y legal',
      visible: true,
      locked: true,
      order: 4,
      elements: [
        {
          id: 'footer-bg',
          type: 'color',
          x: 0,
          y: 720,
          width: 600,
          height: 80,
          fill: '#f8f9fa',
          sectionId: 'footer',
          editable: false,
        },
        {
          id: 'footer-text',
          type: 'text',
          x: 30,
          y: 740,
          width: 540,
          text: '© 2025 Colsanitas. Todos los derechos reservados.\nwww.colsanitas.com | contacto@colsanitas.com',
          fontSize: 12,
          fontFamily: 'Arial, sans-serif',
          fill: '#666666',
          align: 'center',
          sectionId: 'footer',
          editable: false,
        },
      ],
    },
  ],
  metadata: {
    illustratorFile: 'colsanitas-email-template.ai',
    version: '1.0',
    createdAt: '2025-01-12T00:00:00Z',
  },
};

// Plantilla de post para redes sociales
export const socialPostTemplate: Template = {
  id: 'social-post-001',
  name: 'Post Instagram - Colsanitas',
  type: 'post',
  width: 1080,
  height: 1080,
  background: '#ffffff',
  sections: [
    {
      id: 'background',
      name: 'Fondo Principal',
      description: 'Color de fondo del post',
      visible: true,
      locked: false,
      order: 1,
      elements: [
        {
          id: 'main-bg',
          type: 'color',
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          fill: '#0B4B8A',
          sectionId: 'background',
          editable: true,
        },
      ],
    },
    {
      id: 'content',
      name: 'Contenido Principal',
      description: 'Texto e imagen del post',
      visible: true,
      locked: false,
      order: 2,
      elements: [
        {
          id: 'main-title',
          type: 'text',
          x: 80,
          y: 200,
          width: 920,
          text: 'TU SALUD ES\nNUESTRA PRIORIDAD',
          fontSize: 64,
          fontFamily: 'Arial Black, sans-serif',
          fill: '#ffffff',
          align: 'center',
          sectionId: 'content',
          editable: true,
        },
        {
          id: 'main-image',
          type: 'image',
          x: 340,
          y: 450,
          width: 400,
          height: 400,
          src: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDQwMCA0MDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI0MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjRjBGMEYwIiByeD0iMjAiLz4KPHR2ZXh0IHg9IjIwMCIgeT0iMjAwIiBmaWxsPSIjOTk5OTk5IiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMjQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkltYWdlbjwvdGV4dD4KPC9zdmc+Cg==',
          alt: 'Imagen principal del post',
          sectionId: 'content',
          editable: true,
        },
      ],
    },
    {
      id: 'logo',
      name: 'Logo',
      description: 'Logo de Colsanitas',
      visible: true,
      locked: true,
      order: 3,
      elements: [
        {
          id: 'logo-text',
          type: 'text',
          x: 80,
          y: 950,
          text: 'Colsanitas',
          fontSize: 48,
          fontFamily: 'Arial, sans-serif',
          fill: '#ffffff',
          sectionId: 'logo',
          editable: false,
        },
      ],
    },
  ],
  metadata: {
    illustratorFile: 'social-post-template.ai',
    version: '1.0',
    createdAt: '2025-01-12T00:00:00Z',
  },
};

export const defaultTemplates = {
  mail: colsanitasEmailTemplate,
  post: socialPostTemplate,
  // Aquí puedes agregar más plantillas por defecto
  pendon: colsanitasEmailTemplate, // Temporal
  brochure: colsanitasEmailTemplate, // Temporal
};
